version: '3.4'

services:
  platformrecommendation:
    image: platformrecommendation
    build:
      context: node
      dockerfile: ./node/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
        - db
  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    ports: 
      - '27017:27017'
 
volumes:
  mongodata: