version: '3.4'

services:
  platformrecommendation:
    image: node
    build:
      context: .
      dockerfile: node/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PYTHON_HOST=${PYTHON_HOST}
      - PYTHON_PORT=${PYTHON_PORT}
      - PORT=${PORT}
      - HOST=${HOST}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    restart: always
    depends_on:
      - db
      - python
  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    command: [--auth]
    ports: 
      - "27017:27017"
  python:
    image: python
    build: 
      context: .
      dockerfile: python/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  mongodata:
