version: '3.4'

services:
  platformrecommendation:
    image: node
    build:
      context: .
      dockerfile: node/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PYTHON_HOST=${PYTHON_HOST}
      - PYTHON_PORT=${PYTHON_PORT}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
        - db
        - python
  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    ports: 
      - "27017:27017"
  python:
    image: python
    build: 
      context: .
      dockerfile: python/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
  # deploy:
  #   replicas: 3                      # Số lượng container cho dịch vụ
  #   # placement:
  #   #   constraints:
  #   #       - node.role == manager    # Chỉ chạy ở node manager
  #   resources:                        # Thiết lập tài nguyên
  #     limits:                         # Giới hạn tài nguyên
  #       cpus: '2'                  # 50% của 1 Core
  #       memory: 50M 
  #     reservations:                   # Tài nguyên tối thiểu
  #       cpus: '1'
  #       memory: 20M
        
  #   restart_policy:
  #     condition: on-failure

volumes:
  mongodata: